spring:
  application:
    name: p-14134-1
server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: local-ssl
